frr version 9.1-MyOwnFRRVersion
frr defaults traditional
hostname vm-ubuntu
log syslog informational
ip forwarding
no ipv6 forwarding
!
router bgp 65003
 bgp router-id 10.2.0.2
 neighbor 10.2.0.1 remote-as 65002
 neighbor 10.3.0.2 remote-as 65004
 !
 address-family ipv4 unicast
  network 10.101.0.0/24
  neighbor 10.3.0.2 local-role customer
  neighbor 10.3.0.2 route-map AS4 in
  neighbor 10.3.0.2 route-map AS4 out
  neighbor 10.2.0.1 local-role customer
  neighbor 10.2.0.1 route-map AS2 in
  neighbor 10.2.0.1 route-map AS2 out
 exit-address-family
exit
!
route-map AS2 permit 100
 ! lower local preference for AS2 for false positive demo. same as AS4 otherwise.
 set local-preference 300
route-map AS4 permit 100
 set local-preference 300
exit
!
